### ISSUE TITLE
"undefined" unless the tab is loaded

### ISSUE THREAD

**Issue by peter-lyons-kehl** [eyedeekay/Copy-Tab-URL#1]
Thx for Copy-Tab-URL. It does work when the tab has been loaded.

Unfortunately, it doesn't work if the tab is not loaded (for example, a window with tabs restored after a Firefox restart, but the user didn't switch to the tab yet).

If that is an API/Firefox limitation, please add a note to README.md and to https://addons.mozilla.org/firefox/addon/copy-tab-url-to-clipboard.

**Comment by eyedeekay** [comment]
Thanks for the report, I don't think it's a Firefox API limitation, I should be able to fix it. I'll make a new release as soon as I figure it out.

**Comment by eyedeekay** [comment]
Wait, no I didn't understand your issue at first. Yeah, if the tab isn't loaded I don't think Firefox is going to give me a tab ID in any case. So yeah this has got to go into the README.md

**Comment by eyedeekay** [comment]
Changes made. Please confirm that you see the changes here at github and on addons.mozilla.org when you can.
